services:
  chartdb:
    image: ghcr.io/chartdb/chartdb:latest
    container_name: sweetboard-chartdb-dev
    restart: unless-stopped
    ports:
      - "${CHARTDB_HOST_PORT}:${CHARTDB_INTERNAL_PORT}"
    environment:
      DISABLE_ANALITICS: "true"
  test_db:
    image: postgres:18-alpine
    container_name: sweetboard-test-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_TESTDB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TESTDB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TESTDB_DB}
    ports:
      - "${POSTGRES_TESTDB_HOST_PORT}:${POSTGRES_TESTDB_INTERNAL_PORT}"
    volumes:
      - sweetboard_pgdata_test:/var/lib/postgresql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_TESTDB_USER} -d ${POSTGRES_TESTDB_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  sweetboard_pgdata_test:
